# Temporary HTTP-only — used before SSL certs exist
server {
    listen 80;
    listen [::]:80;
    server_name vizara.saxar.uz;

    root /var/www/vizara/dist;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
